#include <student_definition.h>
#include <stdio.h>
#include <iostream>
#include <functions.h>
  void menu(Student *obj)
    {
    int size=2; //because of the two students generated by default for testing
    char g;
    for(int i=0;;i++)
      {
	printf("Please insert command:");
	scanf(" %c",&g);

	if(g=='n') //new student
	  {
	    size++;
	    obj=write(size,obj);
	  }
	  
	else if(g=='c')
	  {
	    int flag=1;
	    size++;
	    do{
	      int temp;
	      printf("Please insert the A.M. of the student that is to be cloned:");
	      scanf("%i",&temp);
	      int f=search(temp,obj,size);
	      if(f!=-1)
		{
		  flag=0;
		  int am;
		  std::string name;
		  printf("Please insert A.M. for the cloned student:");
		  scanf("%i",&am);
		  printf("Please insert the Name of the new student:");
		  scanf(" ");
		  getline(std::cin,name);
		  obj=generate(size,obj);
		  obj[size-1].clone(obj[f],am,name);
		}
	    }while(flag==1);
	    }
	else if(g=='p') //print
	  {
	    int tmp;
	    printf("Please insert A.M. of the student whose table you want to print:");
	    scanf("%i",&tmp);
	    int f=search(tmp,obj,size);
	    if(f+1!=0)
	      obj[f].print();
	  }
	else if(g=='l')
	  {
	    print_all(obj,size);
	  }
	else if(g=='e')
	  {
	    int y;
	    int flag_master=0;
	    do{
	      printf("Please insert the A.M. of the student whose grades you would like to change:");
	      scanf(" %i",&y);
	      int f=search(y,obj,size);
		if(f+1!=0)
		  {
		    std::cout<<"You are editing student "<<obj[f].Name<<"!!"<<std::endl;
		    flag_master=1;//terminates master do{}
		    int flag_subj=0;
		    int d;
		    do{
		      printf("Please insert the subject you would like to change.\n");
		      printf("To add a new subject along with its grade type '-1' :");
		      scanf(" %i",&d);
		      if(d+1==0)		   
			{
			  obj[f].setSub(obj[f].getSub()+1);
			  obj[f].setPts(extend((int) obj[f].getSub(),obj[f].getPts()));
			  float gr;
			  int flag=0;
			  do{
			  printf("Please insert grade for the new subject:");
			  scanf(" %f",&gr);
			  (gr<0||gr>100)?printf("Grade not accepted!!! Please enter grade from 0 to 100!!!\n"):flag=1;
			  }while(flag==0);
			  //printf("%f",gr);
			  //vathmos(f,obj,1);
			  obj[f].grade(obj[f].getSub(),gr);
			  //obj[f].print();
			  char z;
			  int flag_new=0;
			  do{
			    printf("Would you like to change another grade? (y or n) ");
			    scanf(" %c",&z);
			    z=='n'?obj[f].mo(),flag_subj=1,flag_new=1:0;
			      if(z=='y')
				flag_new=1;
			  }while(flag_new-1!=0);
			}
		      else
			{
		    	  std::cout<<"You are editing student "<<obj[f].Name<<"!!"<<std::endl;
			  if(d<=obj[f].getSub())
			    {
			      float grade;
			      int flag=0;
			      do{
			      printf("Please insert new grade:");
			      scanf(" %f",&grade);
			      (grade<0||grade>100)?printf("Grade not accepted!!! Please enter grade from 0 to 100!!!\n"):flag=1;
			      }while(flag==0);
			      obj[f].grade((float) d,grade);
			      char z;
			      int flag_new=0;
			      do{
				printf("Would you like to change another grade? (y or n) ");
				scanf(" %c",&z);
				z=='n'?obj[f].mo(),flag_subj=1,flag_new=1:0;
				if(z=='y')
				  flag_new=1;
			      }while(flag_new-1!=0);
			    }
			  else
				printf("The grade you wish to change doesnt exist!!!!\n");
			}
		    }while(flag_subj-1!=0);
		  }
	      }while(flag_master-1!=0);
	  }
	  
	else if(g=='m') //manual
	  help();
						    
	else if(g=='x') //exit
	  break;
	
	else
	  {
	    printf("............................................................\n");
	    printf("Invalid command!");
	    printf("............................................................\n");
	    help();
	  }
      }
    }
